In [4]:
# Mean Absolute Error
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

def mae(y_true,y_predicted):
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):
        total_error +=abs(yt-yp)
    print(total_error/len(y_true))

In [5]:
mae(y_true,y_predicted)

0.5


In [6]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [8]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [9]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [14]:
# Binary Crossentropy || Log Loss
epsilon = 1e-15

In [24]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [31]:
y_predicted_new = [min(i,1-epsilon) for i in y_prdicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [34]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [35]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844